import React, { useState } from 'react';
import {
  FileSearch,
  ShieldAlert,
  ShieldCheck,
  AlertTriangle,
  UploadCloud,
  FileText,
  Layers,
  Cpu,
  Eye,
  EyeOff,
  CheckCircle2,
  XCircle,
  Clock,
  Download,
  Fingerprint,
  Info,
  RefreshCw,
  Sliders
} from 'lucide-react';

export default function DocumentForensics() {
  const [selectedPreset, setSelectedPreset] = useState('TAMPERED');
  const [analyzing, setAnalyzing] = useState(false);
  const [showHeatmap, setShowHeatmap] = useState(false);
  const [customFile, setCustomFile] = useState(null);

  // Preset Forensic Analysis Cases for Demo
  const presetData = {
    TAMPERED: {
      fileName: 'GST_Registration_Certificate_Doctored.pdf',
      fileSize: '1.24 MB',
      fileType: 'application/pdf (Version 1.7)',
      sha256: '9a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9a8b',
      verdict: 'TAMPERING_DETECTED',
      riskScore: 92,
      producer: 'Adobe Photoshop 24.1 (Windows)',
      creatorTool: 'Canva Web Engine / Raster Exporter',
      creationDate: '2026-08-14 11:22:04 IST',
      modDate: '2026-09-02 18:41:19 IST (19 Days Later)',
      anomalies: [
        {
          id: 'FOR-01',
          type: 'Metadata Discrepancy',
          severity: 'CRITICAL',
          finding: 'Producer metadata contains "Adobe Photoshop 24.1". Official CBIC GST certificates are exclusively generated by "NIC-GSTN Portal Engine (Apache FOP)".',
          impact: 'Conclusive evidence of post-generation graphical manipulation.'
        },
        {
          id: 'FOR-02',
          type: 'Font Dictionary Inconsistency',
          severity: 'HIGH',
          finding: 'Mismatched embedded font in "Turnover Details" bounding box. Rest of certificate uses Roboto-Regular; modified figure uses Arial-Bold with shifted baseline offset (+1.4pt).',
          impact: 'Numeric values altered after original gazette export.'
        },
        {
          id: 'FOR-03',
          type: 'Error Level Analysis (ELA) Variance',
          severity: 'HIGH',
          finding: 'Quantization table frequency mismatch in PAN & Entity Name zone (Block 4, Y:340). Compression noise is 3.8x higher than surrounding background.',
          impact: 'Photoshop patch or layer insertion detected.'
        }
      ],
      recommendation: 'Immediate rejection under GFR 2017 Rule 175. Forfeit EMD and refer to Central Vigilance Commission for statutory forgery investigation.'
    },
    AUTHENTIC: {
      fileName: 'CBIC_GST_REG06_Official.pdf',
      fileSize: '840 KB',
      fileType: 'application/pdf (Version 1.6)',
      sha256: '3f5a7d9c1e2b4f6a8c0e2d4b6f8a0c2e4d6f8a0b2c4e6d8f0a2c4e6b8d0f2a4c',
      verdict: 'AUTHENTIC_VERIFIED',
      riskScore: 4,
      producer: 'NIC-GSTN Digital Certificate Service (Apache FOP v2.6)',
      creatorTool: 'Government of India GSTN Master Portal',
      creationDate: '2026-05-10 09:15:33 IST',
      modDate: '2026-05-10 09:15:33 IST (Exact Match)',
      anomalies: [],
      recommendation: 'Document meets all ISO 27037 forensic standards. Zero digital tampering detected.'
    }
  };

  const activeData = presetData[selectedPreset];

  const handleSelectPreset = (preset) => {
    setAnalyzing(true);
    setSelectedPreset(preset);
    setCustomFile(null);
    setTimeout(() => {
      setAnalyzing(false);
    }, 120);
  };

  const handleFileUpload = (e) => {
    const file = e.target.files[0];
    if (!file) return;
    setCustomFile(file.name);
    setAnalyzing(true);
    setTimeout(() => {
      setAnalyzing(false);
      setSelectedPreset('AUTHENTIC');
    }, 180);
  };

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-5 space-y-4 font-sans">
      {/* 1. Header */}
      <div className="flex flex-col md:flex-row md:items-end justify-between gap-4">
        <div>
          <div className="flex items-center space-x-2 mb-1.5">
            <span className="text-[11px] font-bold uppercase tracking-wider text-[#0B2546] bg-slate-100 border border-slate-300 px-2.5 py-0.5 rounded-full flex items-center gap-1 font-mono">
              <FileSearch className="w-3.5 h-3.5 text-[#0B2546]" />
              <span>Forensic Document Intelligence</span>
            </span>
            <span className="text-slate-300">&bull;</span>
            <span className="text-xs text-slate-500 font-mono">ISO 27037 Digital Forensics &bull; Anti-Forgery Scanner</span>
          </div>
          <h1 className="text-2xl font-black text-[#0B2546] tracking-tight flex items-center gap-2">
            Document Tampering &amp; Metadata Inspector
          </h1>
          <p className="text-xs text-slate-500 mt-1 max-w-3xl">
            Detects graphic manipulation, metadata spoofing (Photoshop/Canva injection), font layer inconsistencies, and Error Level Analysis (ELA) pixel compression variances on submitted vendor certificates.
          </p>
        </div>

        {/* Demo Quick Selectors */}
        <div className="flex items-center gap-2">
          <button
            onClick={() => handleSelectPreset('TAMPERED')}
            className={`px-3 py-1.5 rounded-lg text-xs font-bold transition cursor-pointer flex items-center gap-1.5 ${
              selectedPreset === 'TAMPERED'
                ? 'bg-rose-700 text-white shadow-xs'
                : 'bg-white text-rose-700 border border-rose-200 hover:bg-rose-50'
            }`}
          >
            <ShieldAlert className="w-3.5 h-3.5" />
            <span>Test Tampered File</span>
          </button>

          <button
            onClick={() => handleSelectPreset('AUTHENTIC')}
            className={`px-3 py-1.5 rounded-lg text-xs font-bold transition cursor-pointer flex items-center gap-1.5 ${
              selectedPreset === 'AUTHENTIC'
                ? 'bg-emerald-700 text-white shadow-xs'
                : 'bg-white text-emerald-700 border border-emerald-200 hover:bg-emerald-50'
            }`}
          >
            <ShieldCheck className="w-3.5 h-3.5" />
            <span>Test Authentic File</span>
          </button>
        </div>
      </div>

      {/* 2. Drag & Drop Upload Strip */}
      <div className="bg-white border border-dashed border-slate-300 rounded-xl p-4 text-center hover:border-[#0B2546] transition flex flex-col sm:flex-row items-center justify-between gap-3 shadow-2xs">
        <div className="flex items-center space-x-3 text-left">
          <div className="w-10 h-10 rounded-lg bg-blue-50 border border-blue-200 flex items-center justify-center shrink-0">
            <UploadCloud className="w-5 h-5 text-[#0B2546]" />
          </div>
          <div>
            <span className="text-xs font-bold text-slate-800 block">
              {customFile ? `Uploaded Custom File: ${customFile}` : 'Upload Any Vendor Certificate for Deep Forensic Audit'}
            </span>
            <span className="text-[11px] text-slate-400">
              Accepts PDF, scanned TIFF, or PNG &bull; Runs local metadata string parsing &amp; quantisation tests
            </span>
          </div>
        </div>

        <label className="px-4 py-2 bg-[#0B2546] hover:bg-[#123663] text-white text-xs font-bold rounded-lg transition shadow-xs cursor-pointer shrink-0">
          <span>Choose File to Inspect</span>
          <input type="file" accept=".pdf,.png,.jpg,.jpeg" onChange={handleFileUpload} className="hidden" />
        </label>
      </div>

      {/* 3. Forensic Loading State */}
      {analyzing ? (
        <div className="bg-white border border-slate-200 rounded-xl p-12 text-center text-slate-500">
          <RefreshCw className="w-8 h-8 mx-auto animate-spin text-[#0B2546] mb-2" />
          <span className="text-xs font-bold text-slate-700">
            Executing Byte-Stream Metadata Scan &amp; Quantization Matrix...
          </span>
        </div>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-5">
          {/* Left: Document Metadata & Forensic Telemetry (7 Cols) */}
          <div className="lg:col-span-7 space-y-4">
            {/* Verdict Card */}
            <div
              className={`p-4 rounded-xl border flex items-center justify-between shadow-2xs ${
                activeData.verdict === 'TAMPERING_DETECTED'
                  ? 'bg-rose-50 border-rose-200 text-rose-950'
                  : 'bg-emerald-50 border-emerald-200 text-emerald-950'
              }`}
            >
              <div className="flex items-center space-x-3">
                {activeData.verdict === 'TAMPERING_DETECTED' ? (
                  <XCircle className="w-6 h-6 text-rose-600 shrink-0" />
                ) : (
                  <CheckCircle2 className="w-6 h-6 text-emerald-600 shrink-0" />
                )}
                <div>
                  <span className="text-xs font-black font-mono uppercase tracking-wider block">
                    {activeData.verdict === 'TAMPERING_DETECTED'
                      ? 'HIGH PROBABILITY OF DIGITAL FORGERY'
                      : 'OFFICIAL UNMODIFIED CERTIFICATE'}
                  </span>
                  <span className="text-[11px] font-medium opacity-80">
                    {activeData.verdict === 'TAMPERING_DETECTED'
                      ? 'Metadata and font layers contain severe inconsistencies with official gazetted formats.'
                      : 'Byte structure and digital signature verified against National Informatics Centre (NIC) spec.'}
                  </span>
                </div>
              </div>

              <div className="text-right shrink-0">
                <span className="text-[9px] font-mono font-bold uppercase block opacity-70">
                  Tamper Risk
                </span>
                <span
                  className={`text-xl font-black font-mono ${
                    activeData.verdict === 'TAMPERING_DETECTED' ? 'text-rose-700' : 'text-emerald-700'
                  }`}
                >
                  {activeData.riskScore}%
                </span>
              </div>
            </div>

            {/* Metadata Telemetry Box */}
            <div className="bg-white border border-slate-200 rounded-xl p-4 shadow-2xs space-y-3">
              <div className="flex items-center justify-between border-b border-slate-100 pb-2.5">
                <div className="flex items-center space-x-2">
                  <Cpu className="w-4 h-4 text-[#0B2546]" />
                  <h3 className="text-xs font-extrabold uppercase tracking-wider text-slate-800 font-mono">
                    Low-Level PDF Stream Metadata Telemetry
                  </h3>
                </div>
                <span className="text-[10px] font-mono font-bold text-slate-400">
                  {activeData.fileType}
                </span>
              </div>

              <div className="grid grid-cols-2 gap-3 text-xs">
                <div>
                  <span className="text-[10px] font-bold text-slate-400 font-mono uppercase block">
                    Generating Producer Application
                  </span>
                  <span
                    className={`font-mono font-bold mt-0.5 block ${
                      activeData.verdict === 'TAMPERING_DETECTED' ? 'text-rose-700 bg-rose-50 p-1 rounded border border-rose-200' : 'text-slate-800'
                    }`}
                  >
                    {activeData.producer}
                  </span>
                </div>

                <div>
                  <span className="text-[10px] font-bold text-slate-400 font-mono uppercase block">
                    Authoring Tool / Software
                  </span>
                  <span className="font-mono font-semibold text-slate-800 mt-0.5 block">
                    {activeData.creatorTool}
                  </span>
                </div>

                <div>
                  <span className="text-[10px] font-bold text-slate-400 font-mono uppercase block">
                    Original Creation Timestamp
                  </span>
                  <span className="font-mono text-slate-700 mt-0.5 block">
                    {activeData.creationDate}
                  </span>
                </div>

                <div>
                  <span className="text-[10px] font-bold text-slate-400 font-mono uppercase block">
                    Last Modified Timestamp
                  </span>
                  <span
                    className={`font-mono font-semibold mt-0.5 block ${
                      activeData.verdict === 'TAMPERING_DETECTED' ? 'text-amber-700' : 'text-slate-700'
                    }`}
                  >
                    {activeData.modDate}
                  </span>
                </div>
              </div>

              {/* SHA-256 Checksum */}
              <div className="pt-2 border-t border-slate-100">
                <span className="text-[10px] font-bold text-slate-400 font-mono uppercase block">
                  Cryptographic SHA-256 Checksum
                </span>
                <span className="font-mono text-[10px] text-slate-600 bg-slate-50 p-1.5 rounded border border-slate-200 block truncate mt-0.5">
                  {activeData.sha256}
                </span>
              </div>
            </div>

            {/* Detected Forensic Anomalies */}
            <div className="bg-white border border-slate-200 rounded-xl p-4 shadow-2xs space-y-3">
              <h3 className="text-xs font-extrabold uppercase tracking-wider text-slate-800 font-mono flex items-center justify-between">
                <span>Forensic Discrepancy Findings ({activeData.anomalies.length})</span>
                <span className="text-[10px] font-normal text-slate-400">Byte &amp; Font Layer Integrity</span>
              </h3>

              {activeData.anomalies.length > 0 ? (
                <div className="space-y-2.5">
                  {activeData.anomalies.map((anom) => (
                    <div
                      key={anom.id}
                      className="bg-slate-50 border border-slate-200 rounded-lg p-3 text-xs space-y-1"
                    >
                      <div className="flex items-center justify-between">
                        <span className="font-black text-rose-800 font-mono text-[11px] flex items-center gap-1.5">
                          <AlertTriangle className="w-3.5 h-3.5 text-rose-600" />
                          {anom.type}
                        </span>
                        <span className="text-[9px] font-mono font-bold px-1.5 py-0.2 rounded bg-rose-100 text-rose-800 border border-rose-300">
                          {anom.severity}
                        </span>
                      </div>
                      <p className="text-slate-700 leading-relaxed text-[11px]">{anom.finding}</p>
                      <span className="text-[10px] text-slate-500 font-medium block">
                        <span className="font-bold">Legal Impact:</span> {anom.impact}
                      </span>
                    </div>
                  ))}
                </div>
              ) : (
                <div className="bg-emerald-50/70 border border-emerald-200 rounded-lg p-3 text-xs text-emerald-900 flex items-center gap-2 font-medium">
                  <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" />
                  <span>All PostScript font streams and XMP metadata packets strictly conform to official NIC specifications.</span>
                </div>
              )}
            </div>
          </div>

          {/* Right: Visual Forensic Heatmap / Certificate Preview (5 Cols) */}
          <div className="lg:col-span-5 space-y-4">
            <div className="bg-white border border-slate-200 rounded-xl p-4 shadow-2xs space-y-3">
              <div className="flex items-center justify-between">
                <span className="text-xs font-bold uppercase tracking-wider text-slate-700 font-mono">
                  Visual Forensic Viewport
                </span>
                <button
                  onClick={() => setShowHeatmap(!showHeatmap)}
                  className={`px-2.5 py-1 text-xs font-bold rounded-md transition flex items-center gap-1 cursor-pointer ${
                    showHeatmap
                      ? 'bg-rose-700 text-white'
                      : 'bg-slate-100 text-slate-700 hover:bg-slate-200'
                  }`}
                >
                  {showHeatmap ? <EyeOff className="w-3 h-3" /> : <Eye className="w-3 h-3" />}
                  <span>{showHeatmap ? 'Standard View' : 'ELA Noise Heatmap'}</span>
                </button>
              </div>

              {/* Certificate Canvas / Mock Display */}
              <div className="relative border border-slate-300 rounded-lg overflow-hidden bg-slate-100 p-4 aspect-[3/4] flex flex-col justify-between text-slate-800 text-[10px]">
                {/* Certificate Watermark Header */}
                <div className="text-center border-b border-slate-300 pb-2 space-y-0.5">
                  <span className="font-bold uppercase tracking-wider text-slate-600 block text-[9px] font-mono">
                    Government of India &bull; Form GST REG-06
                  </span>
                  <span className="text-xs font-extrabold text-[#0B2546] block">
                    Registration Certificate
                  </span>
                </div>

                {/* Certificate Mock Rows */}
                <div className="space-y-3 py-4 flex-1">
                  <div>
                    <span className="text-slate-400 font-bold block">1. Legal Name of Business:</span>
                    <span className="font-bold text-slate-900 text-xs">
                      {selectedPreset === 'TAMPERED' ? 'Apex Industrial Valves Ltd' : 'Bharat Petroleum Supplies Ltd'}
                    </span>
                  </div>

                  <div>
                    <span className="text-slate-400 font-bold block">2. Trade Name:</span>
                    <span className="font-semibold text-slate-800">Industrial Valve Supply Div</span>
                  </div>

                  <div className="relative">
                    <span className="text-slate-400 font-bold block">3. Registration Number (GSTIN):</span>
                    <span
                      className={`font-mono font-extrabold text-xs block ${
                        selectedPreset === 'TAMPERED' && showHeatmap
                          ? 'bg-rose-500/80 text-white px-1 rounded animate-pulse'
                          : 'text-[#0B2546]'
                      }`}
                    >
                      33AAACA9988C1Z2
                    </span>
                    {selectedPreset === 'TAMPERED' && showHeatmap && (
                      <span className="absolute -top-3 right-0 text-[8px] font-mono font-bold text-rose-700 bg-rose-100 px-1 rounded border border-rose-300">
                        [ELA Artifact: Re-compressed Block]
                      </span>
                    )}
                  </div>

                  <div className="relative">
                    <span className="text-slate-400 font-bold block">4. Annual Turnover Declaration:</span>
                    <span
                      className={`font-mono font-extrabold text-xs block ${
                        selectedPreset === 'TAMPERED' && showHeatmap
                          ? 'bg-rose-500/80 text-white px-1 rounded animate-pulse'
                          : 'text-slate-900'
                      }`}
                    >
                      ₹48,20,00,000 (INR 48.20 Cr)
                    </span>
                    {selectedPreset === 'TAMPERED' && showHeatmap && (
                      <span className="absolute -top-3 right-0 text-[8px] font-mono font-bold text-rose-700 bg-rose-100 px-1 rounded border border-rose-300">
                        [Font Mismatch: Arial-Bold Overlay]
                      </span>
                    )}
                  </div>
                </div>

                {/* Certificate Footer Stamp */}
                <div className="pt-2 border-t border-slate-300 flex items-center justify-between text-[9px] text-slate-500">
                  <span>Jurisdiction: Manali Division, Chennai</span>
                  <span className="font-mono">Date: 10/05/2026</span>
                </div>

                {/* Heatmap Overlay Grid (Active when toggled) */}
                {showHeatmap && (
                  <div className="absolute inset-0 bg-rose-900/10 pointer-events-none flex flex-col justify-between p-2">
                    <div className="text-right">
                      <span className="text-[9px] font-mono font-bold bg-rose-700 text-white px-1.5 py-0.5 rounded shadow-xs">
                        ELA Sensitivity: 95%
                      </span>
                    </div>
                  </div>
                )}
              </div>

              {/* Vigilance Action Directive */}
              <div className="pt-2">
                <span className="text-[10px] font-bold text-slate-400 font-mono uppercase block mb-1">
                  Vigilance Directive
                </span>
                <p className="text-[11px] text-slate-700 bg-slate-50 p-2.5 rounded border border-slate-200 leading-tight">
                  {activeData.recommendation}
                </p>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
